export const BUILTIN_TEMPLATES = [
  {
    id: 'tpl-product-closeup',
    name: 'Produkt-Nahaufnahme',
    icon: '🔍',
    description: 'Einzelprodukt oder wenige Objekte, clean Background, Studio-Beleuchtung',
    typical_use: 'Produktseite, Katalog',
    prompt_template: 'Professional product photography. Clean white or neutral background with soft studio lighting. Sharp focus on the main product with subtle shadows. The following materials are placed in the scene: {materials}. Photorealistic, commercial quality, 2K resolution.',
  },
  {
    id: 'tpl-flat-lay',
    name: 'Flat Lay',
    icon: '🖼️',
    description: 'Draufsicht auf arrangierte Materialien auf einer Oberfläche',
    typical_use: 'Instagram, Pinterest',
    prompt_template: 'Flat lay photography from directly above. Materials are artfully arranged on a wooden table or marble surface. Soft natural light from the side. The following materials are visible: {materials}. Photorealistic, Instagram-worthy composition.',
  },
  {
    id: 'tpl-person-painting',
    name: 'Person malt',
    icon: '🎨',
    description: 'Lifestyle-Szene: Hände oder Person beim Ausmalen eines MNZ-Bildes',
    typical_use: 'Social Media, Werbung',
    prompt_template: 'Lifestyle photography showing hands or a person painting a paint-by-numbers canvas. Warm, cozy atmosphere. Only these items may be visible in the scene: {materials}. Natural light, shallow depth of field on the painting activity. Authentic, relatable moment.',
  },
  {
    id: 'tpl-living-room',
    name: 'Wohnzimmer-Setting',
    icon: '🏠',
    description: 'Fertiges Bild an der Wand oder Malstation im Wohnzimmer',
    typical_use: 'Hero-Banner, Lifestyle',
    prompt_template: 'Interior photography of a stylish living room. A finished paint-by-numbers artwork displayed prominently. Only these materials may be visible: {materials}. Warm ambient lighting, modern Scandinavian design. The artwork is the focal point.',
  },
  {
    id: 'tpl-macro-detail',
    name: 'Macro-Detail',
    icon: '🔬',
    description: 'Extreme Nahaufnahme: Pinselstriche, Farbpigmente, Leinwand-Textur',
    typical_use: 'Social Creatives, Reels',
    prompt_template: 'Extreme macro photography showing fine details of the following only: {materials}. Very shallow depth of field with beautiful bokeh. Ultra-sharp detail, 2K resolution.',
  },
  {
    id: 'tpl-unboxing',
    name: 'Unboxing / Geschenk',
    icon: '🎁',
    description: 'Verpackung, Auspacken oder Geschenk-Situation',
    typical_use: 'Produktseite, Werbung',
    prompt_template: 'Unboxing scene or gift-giving moment. A paint-by-numbers kit is being unwrapped or presented as a gift. Contents visible: {materials}. Warm, inviting atmosphere with excitement and anticipation.',
  },
  {
    id: 'tpl-natural-light',
    name: 'Natürliches Licht',
    icon: '☀️',
    description: 'Warmes Fensterlicht, gemütliche Atmosphäre',
    typical_use: 'Blog, Lifestyle',
    prompt_template: 'Beautiful natural window light photography. Warm morning or golden hour light streaming in. Creative workspace. Only these materials may be visible: {materials}. Soft shadows, warm color temperature, hygge atmosphere. Photorealistic.',
  },
  {
    id: 'tpl-white-background',
    name: 'Weißer Hintergrund',
    icon: '⬜',
    description: 'Klassisches Produktfoto, freigestellt auf weißem Hintergrund',
    typical_use: 'Shop, Marktplatz-Listings',
    prompt_template: 'Product photography on pure white background. Clean, professional, e-commerce ready. No shadows or minimal soft shadow. Materials clearly visible with accurate colors: {materials}. Perfect for online shop listings.',
  },
  {
    id: 'tpl-gallery-vernissage',
    name: 'Gallery Vernissage',
    icon: '🖼️',
    description: 'Elegante Galerie-Präsentation, mehrere gerahmte Motive an weißen Wänden',
    typical_use: 'Motiv-Präsentation, Portfolio',
    prompt_template: 'Contemporary art gallery exhibition photography. Multiple framed paint-by-numbers artworks displayed on pristine white gallery walls with professional track lighting. Clean, minimalist gallery space with wooden floor. The artworks feature: {materials}. Museum-quality presentation, sophisticated atmosphere, 2K resolution.',
  },
  {
    id: 'tpl-artist-studio',
    name: 'Künstler-Atelier',
    icon: '🎨',
    description: 'Authentisches Atelier mit mehreren Werken in verschiedenen Stadien',
    typical_use: 'Behind-the-scenes, Motiv-Kollektion',
    prompt_template: 'Artist studio photography with authentic creative atmosphere. Natural north light through large windows. Only these materials may appear in the scene: {materials}. Inspiring, creative workspace. Photorealistic.',
  },
  {
    id: 'tpl-modern-boutique',
    name: 'Moderne Boutique',
    icon: '🏬',
    description: 'Stilvoller Boutique-/Shop-Display mit hochwertiger Präsentation',
    typical_use: 'Retail-Präsentation, Motiv-Launch',
    prompt_template: 'Modern boutique interior photography. High-end retail display showcasing paint-by-numbers kits as premium lifestyle products. Minimalist Scandinavian design with natural wood shelving and soft ambient lighting. Featured products: {materials}. Elegant presentation with plants and design elements. Professional retail photography.',
  },
  {
    id: 'tpl-exhibition-wall',
    name: 'Ausstellungs-Wand',
    icon: '🏛️',
    description: 'Professionelle Ausstellungswand mit Grid-Layout, Museum-Stil',
    typical_use: 'Portfolio, Motiv-Übersicht',
    prompt_template: 'Museum exhibition wall photography. A curated grid of framed artworks displayed with perfect symmetry on a textured gallery wall. Professional gallery lighting creating subtle highlights. The collection includes: {materials}. Sophisticated, editorial-quality presentation. 2K resolution, architectural photography style.',
  },
  {
    id: 'tpl-creative-corner',
    name: 'Kreativ-Ecke',
    icon: '✨',
    description: 'Gemütliche Kreativ-Ecke mit inspirierender Atmosphäre',
    typical_use: 'Social Media, Lifestyle-Content',
    prompt_template: 'Cozy creative corner photography. A dedicated art space with inspiring decor, fairy lights, and plants. Multiple paint-by-numbers projects displayed on walls and shelves. Materials visible: {materials}. Warm, inviting atmosphere with personal touches. Instagram-worthy aesthetic, golden hour lighting.',
  },
  {
    id: 'tpl-wall-collection',
    name: 'Wandcollage',
    icon: '🎭',
    description: 'Organische Wandcollage mit verschiedenen Rahmengrößen',
    typical_use: 'Motiv-Kollektion, Home Decor',
    prompt_template: 'Gallery wall photography featuring an organic arrangement of various sized frames. Mix of landscape and portrait orientations creating a cohesive wall art collection. The artworks include: {materials}. Modern interior with neutral wall color, natural lighting. Professional interior design photography.',
  },
  {
    id: 'tpl-luxury-showcase',
    name: 'Luxury Showcase',
    icon: '💎',
    description: 'Premium-Präsentation mit edlen Materialien und Beleuchtung',
    typical_use: 'Premium-Produkte, Sonderkollektionen',
    prompt_template: 'Luxury product showcase photography. High-end presentation with premium materials like marble, brass accents, and velvet. Dramatic spot lighting creating sophisticated shadows. Featured items: {materials}. Opulent, editorial-quality photography for premium products. Magazine-worthy composition.',
  },
  {
    id: 'tpl-minimalist-showcase',
    name: 'Minimalist Showcase',
    icon: '⚪',
    description: 'Ultra-minimalistisch mit Fokus auf das Motiv',
    typical_use: 'Portfolio, Art Prints',
    prompt_template: 'Ultra-minimalist showcase photography. Single artwork or small collection displayed with absolute simplicity. Pure white or concrete backdrop, natural diffused lighting. Featured: {materials}. Zen-like simplicity, Scandinavian aesthetic. Focus entirely on the artwork itself. High-end gallery photography.',
  },
];
